// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAvatar: typeof import("ant-design-vue/es")["Avatar"]
    ABreadcrumb: typeof import("ant-design-vue/es")["Breadcrumb"]
    ABreadcrumbItem: typeof import("ant-design-vue/es")["BreadcrumbItem"]
    AButton: typeof import("ant-design-vue/es")["Button"]
    ACard: typeof import("ant-design-vue/es")["Card"]
    ACheckbox: typeof import("ant-design-vue/es")["Checkbox"]
    ACollapse: typeof import("ant-design-vue/es")["Collapse"]
    ACollapsePanel: typeof import("ant-design-vue/es")["CollapsePanel"]
    AConfigProvider: typeof import("ant-design-vue/es")["ConfigProvider"]
    ADatePicker: typeof import("ant-design-vue/es")["DatePicker"]
    ADrawer: typeof import("ant-design-vue/es")["Drawer"]
    ADropdown: typeof import("ant-design-vue/es")["Dropdown"]
    AForm: typeof import("ant-design-vue/es")["Form"]
    AFormItem: typeof import("ant-design-vue/es")["FormItem"]
    AInput: typeof import("ant-design-vue/es")["Input"]
    AInputPassword: typeof import("ant-design-vue/es")["InputPassword"]
    ALayout: typeof import("ant-design-vue/es")["Layout"]
    ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"]
    ALayoutFooter: typeof import("ant-design-vue/es")["LayoutFooter"]
    ALayoutHeader: typeof import("ant-design-vue/es")["LayoutHeader"]
    ALayoutSider: typeof import("ant-design-vue/es")["LayoutSider"]
    AList: typeof import("ant-design-vue/es")["List"]
    AListItem: typeof import("ant-design-vue/es")["ListItem"]
    AListItemMeta: typeof import("ant-design-vue/es")["ListItemMeta"]
    AMenu: typeof import("ant-design-vue/es")["Menu"]
    AMenuItem: typeof import("ant-design-vue/es")["MenuItem"]
    ARadio: typeof import("ant-design-vue/es")["Radio"]
    ARangePicker: typeof import("ant-design-vue/es")["RangePicker"]
    AResult: typeof import("ant-design-vue/es")["Result"]
    ASelect: typeof import("ant-design-vue/es")["Select"]
    ASelectOption: typeof import("ant-design-vue/es")["SelectOption"]
    ASubMenu: typeof import("ant-design-vue/es")["SubMenu"]
    ASwitch: typeof import("ant-design-vue/es")["Switch"]
    ATable: typeof import("ant-design-vue/es")["Table"]
    Result: typeof import("./../src/components/Result.vue")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
  }
}
